spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fund_dump
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#  https://blog.csdn.net/long690276759/article/details/82259550
    hikari:
      # 最大连接数
      maximum-pool-size: 50
      minimum-idle: 10
      pool-name: fund_dump_datapool
      auto-commit: true
      idle-timeout: 10
      max-lifetime: 50
      connection-test-query: select '1'
      connection-timeout: 30000
mybatis:
  mapper-locations: classpath*:/mappers/*.xml


